# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ui\activation_dlg.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_activation_dlg(object):
    def setupUi(self, activation_dlg):
        activation_dlg.setObjectName("activation_dlg")
        activation_dlg.resize(488, 261)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(activation_dlg.sizePolicy().hasHeightForWidth())
        activation_dlg.setSizePolicy(sizePolicy)
        self.verticalLayout = QtWidgets.QVBoxLayout(activation_dlg)
        self.verticalLayout.setObjectName("verticalLayout")
        self.logo = QtWidgets.QLabel(activation_dlg)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.logo.sizePolicy().hasHeightForWidth())
        self.logo.setSizePolicy(sizePolicy)
        self.logo.setMinimumSize(QtCore.QSize(470, 109))
        self.logo.setMaximumSize(QtCore.QSize(470, 109))
        self.logo.setObjectName("logo")
        self.verticalLayout.addWidget(self.logo)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(activation_dlg)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.editKey = QtWidgets.QLineEdit(activation_dlg)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.editKey.sizePolicy().hasHeightForWidth())
        self.editKey.setSizePolicy(sizePolicy)
        self.editKey.setObjectName("editKey")
        self.verticalLayout_2.addWidget(self.editKey)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.editInfo = QtWidgets.QTextEdit(activation_dlg)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.editInfo.sizePolicy().hasHeightForWidth())
        self.editInfo.setSizePolicy(sizePolicy)
        self.editInfo.setMaximumSize(QtCore.QSize(16777215, 80))
        self.editInfo.setReadOnly(True)
        self.editInfo.setObjectName("editInfo")
        self.horizontalLayout.addWidget(self.editInfo)
        self.btnOK = QtWidgets.QPushButton(activation_dlg)
        self.btnOK.setMinimumSize(QtCore.QSize(100, 0))
        self.btnOK.setObjectName("btnOK")
        self.horizontalLayout.addWidget(self.btnOK)
        self.btnCancel = QtWidgets.QPushButton(activation_dlg)
        self.btnCancel.setMinimumSize(QtCore.QSize(100, 0))
        self.btnCancel.setObjectName("btnCancel")
        self.horizontalLayout.addWidget(self.btnCancel)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(activation_dlg)
        QtCore.QMetaObject.connectSlotsByName(activation_dlg)

    def retranslateUi(self, activation_dlg):
        _translate = QtCore.QCoreApplication.translate
        activation_dlg.setWindowTitle(_translate("activation_dlg", "About DICE"))
        self.logo.setText(_translate("activation_dlg", "logo"))
        self.label.setText(_translate("activation_dlg", "Enter the activation key"))
        self.btnOK.setText(_translate("activation_dlg", "OK"))
        self.btnCancel.setText(_translate("activation_dlg", "Cancel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    activation_dlg = QtWidgets.QDialog()
    ui = Ui_activation_dlg()
    ui.setupUi(activation_dlg)
    activation_dlg.show()
    sys.exit(app.exec_())
