# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ui\log_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_log_widget(object):
    def setupUi(self, log_widget):
        log_widget.setObjectName("log_widget")
        log_widget.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(log_widget)
        self.verticalLayout.setContentsMargins(0, 9, 9, 9)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.plain_text_edit_log = QtWidgets.QPlainTextEdit(log_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.plain_text_edit_log.sizePolicy().hasHeightForWidth())
        self.plain_text_edit_log.setSizePolicy(sizePolicy)
        self.plain_text_edit_log.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.plain_text_edit_log.setReadOnly(True)
        self.plain_text_edit_log.setObjectName("plain_text_edit_log")
        self.verticalLayout.addWidget(self.plain_text_edit_log)

        self.retranslateUi(log_widget)
        QtCore.QMetaObject.connectSlotsByName(log_widget)

    def retranslateUi(self, log_widget):
        _translate = QtCore.QCoreApplication.translate
        log_widget.setWindowTitle(_translate("log_widget", "Form"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    log_widget = QtWidgets.QWidget()
    ui = Ui_log_widget()
    ui.setupUi(log_widget)
    log_widget.show()
    sys.exit(app.exec_())
