# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ui\progress_dlg.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_progress_dlg(object):
    def setupUi(self, progress_dlg):
        progress_dlg.setObjectName("progress_dlg")
        progress_dlg.resize(600, 82)
        self.verticalLayout = QtWidgets.QVBoxLayout(progress_dlg)
        self.verticalLayout.setObjectName("verticalLayout")
        self.progress_bar = QtWidgets.QProgressBar(progress_dlg)
        self.progress_bar.setMinimum(0)
        self.progress_bar.setMaximum(100)
        self.progress_bar.setProperty("value", 0)
        self.progress_bar.setObjectName("progress_bar")
        self.verticalLayout.addWidget(self.progress_bar)
        self.lbl_info = QtWidgets.QLabel(progress_dlg)
        self.lbl_info.setObjectName("lbl_info")
        self.verticalLayout.addWidget(self.lbl_info)

        self.retranslateUi(progress_dlg)
        QtCore.QMetaObject.connectSlotsByName(progress_dlg)

    def retranslateUi(self, progress_dlg):
        _translate = QtCore.QCoreApplication.translate
        progress_dlg.setWindowTitle(_translate("progress_dlg", "Progressing..."))
        self.lbl_info.setText(_translate("progress_dlg", "TextLabel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    progress_dlg = QtWidgets.QDialog()
    ui = Ui_progress_dlg()
    ui.setupUi(progress_dlg)
    progress_dlg.show()
    sys.exit(app.exec_())
